name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Passo 1: Faz o checkout do código
    - name: Checkout code
      uses: actions/checkout@v4

    # Passo 2: Configura o Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    # Passo 3: Instala as dependências do Python
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov

    # Passo 4: Roda os testes
    - name: Run tests
      run: pytest --cov=.
      continue-on-error: false
