name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov

    - name: Run tests
      run: |
        set -e  # Isso vai fazer o fluxo parar caso algum comando falhe
        pytest --cov=.

    # Commit changes (isso s칩 ser치 executado se os testes passarem)
    - name: Commit changes
      if: success()  # Isso garante que o commit s칩 ser치 feito se os testes passarem
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Add coverage report"
        git push
